<?
$aMenuLinks = Array(
    Array(
        "Главная",
        "/",
        Array(),
        Array("ICON_CLASS"=>"icon-home4"),
        ""
    ),
    Array(
        "Каталог",
        "/orders/blank_zakaza/",
        Array(),
        Array("IS_CATALOG"=>"Y"),
        ""
    ),
    Array(
        "Мои организации",
        "/personal/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Заказы",
        "/orders/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Документы",
        "/documents/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "О нас",
        "/about/",
        Array(),
        Array(),
        ""
    )
);
?>